### ISSUE TITLE
Easy way to get status page up and running without k8s

### ISSUE THREAD

**Issue by fkr** [joshmue/scs-status-page-web#1]
While the usual deployment could (should?) be done via k8s, there are cases where it is OK to run this in a single deployment.
I'd like us to provide such a way.

**Comment by joshmue** [comment]
Options:
- Supply `docker-compose` file
  - referring to built images in registries, not building them at runtime
- Supply K8s Pod manifests consumable by `podman play kube`
- Supply systemd unit files executing `docker/podman run ...`

All of the above options most likely will require the operator to copy the manifest(s), modify it to their needs and keep porting any upstream changes.

More options:

- Supply "all in one" container image
  - including supervising init which starts postgres, api server, web server and reverse proxy
  - may be configurable via env vars etc.
- Supply non-containerized distribution packages (deb, rpm, etc.) via e.g. fpm
  - "native" to distribution tooling and traditional automation tools like ansible, puppet etc.

**Comment by fkr** [comment]
I will make an attempt at setting it up with podman and will document those steps.

**Comment by fkr** [comment]
To be done by @fkr in CW8. Either done in CW8 or not at all.

**Comment by fkr** [comment]
not needed anymore
